DROP TABLE IF EXISTS USER_TABLE;
create table USER_TABLE(
	USER_NO int not null AUTO_INCREMENT,
	EMAIL VARCHAR(50),
	PASSWORD VARCHAR(200),
    PRIMARY KEY(USER_NO)
);

DROP TABLE IF EXISTS DOCUMENT_TRANS;
create table DOCUMENT_TRANS(
	DOCUMENT_NO int not null AUTO_INCREMENT,
    USER_NO int not null,
    TRANS_DATE DATE,
	INPUT TEXT,
	OUTPUT VARCHAR(200),
    PRIMARY KEY(DOCUMENT_NO),
    FOREIGN KEY(USER_NO) REFERENCES USER_TABLE (USER_NO) ON DELETE CASCADE
);

DROP TABLE IF EXISTS MEDIA_TRANS;
create table MEDIA_TRANS(
	MEDIA_NO int not null AUTO_INCREMENT,
    USER_NO int not null,
    TRANS_DATE DATE,
    KIND VARCHAR(20),
	INPUT VARCHAR(200),
	OUTPUT TEXT,
     PRIMARY KEY(MEDIA_NO),
    FOREIGN KEY(USER_NO) REFERENCES USER_TABLE (USER_NO) ON DELETE CASCADE
);

DROP TABLE IF EXISTS TRANSLATION_TRANS;
create table TRANSLATION_TRANS(
	TRANSLATION_NO int not null AUTO_INCREMENT,
    USER_NO int not null,
    TRANS_DATE DATE,
	INPUT TEXT,
	OUTPUT TEXT,
     PRIMARY KEY(TRANSLATION_NO),
    FOREIGN KEY(USER_NO) REFERENCES USER_TABLE (USER_NO) ON DELETE CASCADE
);
